### ISSUE TITLE
Angular rail detector set to on mouse out

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-component-library#216]
#### Describe the bug

The navigation rail's active item color doesn't change until the user moves the mouse out. This only seems to happen when a rail is inside the drawerLayout.

#### What is the expected behavior?

Should behave.

#### What are the steps to reproduce?
1. Go to https://pxblue-components.github.io/angular-dev/?path=/story/components-drawer--within-a-drawer-layout 
2. Set variant to rail
3. Click around but don't move the mouse cursor out of the rail area. Observe that the color won't change
4. Move the mouse out. Now you see the color applied correctly.

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/8997218/105866264-d0b85400-5fc1-11eb-8720-49103860a080.mov

#### Environment
MacOS Chrome
		
#### Anything else to add?
Only seen on storybook so far.

**Comment by emclaug2** [comment]
This is 100% a storybook issue.  There's a couple solutions here that come to mind, none of which are _good_ fixes. 

1. Wrap the DrawerLayout story in a component so that we can manually invoke change detection whenever the variant changes.  This will render our story source tab useless in storybook, so this is why I want to avoid this solution (might not work).
2. Split the DrawerLayout story into 2.  One for all non-rail variants.   
3. Remove rail variant from the DrawerLayout story.

**Comment by jeffvg** [comment]
This is storybook issue and could be fixed with latest version of Story Book.
* Look in to option 2 (Split the DrawerLayout story into 2. One for all non-rail variants.)
