### ISSUE TITLE
Dark theme Hero Background

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#217]
#### Describe the desired behavior
Hero background image should be reflective of light or dark theme.

#### Describe the current behavior
Background color is hard-coded inside the component library to be white, regardless of whether the theme is light or dark.

#### Is this request related to a current issue?
No

#### Additional Context

No

**Comment by huayunh** [comment]
As for the "white letter A with dark background" problem 

![image](https://user-images.githubusercontent.com/8997218/105895444-8647cf00-5fe3-11eb-8c06-8ad7a6cced98.png)

— I suppose the designers can provide their own custom svg for the developers to implement as a substitute for the icon. So for this story, just implement the hero component so that the background color matches the card background

**Comment by emclaug2** [comment]
Oof this is my mistake; the background color was not hard-coded to be white inside the component library.  It was hardcoded to be white inside the storybook story.  I'll have a fix out for this soon.

**Comment by emclaug2** [comment]
Right now it's pretty easy to manually add the necessary colors for the badge background color.  @joebochill  Do you think it makes sense to have these light/dark badge background defaults as part of the angular theme?

**Comment by joebochill** [comment]
I think it would be good to have the defaults set so that someone who sets up light/dark themes for their application don't have to conditionally add a background color prop for the dark theme (we should handle that logic for them).

**Comment by emclaug2** [comment]
Ok I'll move this fix from the storybook + showcase to the theme repo.

**Comment by emclaug2** [comment]
Fixed here: https://github.com/pxblue/themes/pull/133
